### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
Fixes issue #11 
@ijpulidos can you double-check the version pinning? We want at least version 3.0.6, but don't want to pull in 4.x

**Comment by mikemhenry** [comment]
Also, just in case our perses release gets held up, I wanted to get this one out so that it will be easier to build a perses 0.9.2 env for future testing and benchmarking.

**Review by ijpulidos — APPROVED** [review]
Looks good to me. Thanks!

**Comment by mikemhenry** [comment]
oops, will fix that! :point_up:

**Comment by mikemhenry** [comment]
closing this in favor of this PR 
https://github.com/conda-forge/perses-feedstock/pull/13

**Pull request closed without merging**
