### PR TITLE
Create meta.yaml

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
@conda-forge-admin, please rerender

**Comment by mikemhenry** [comment]
Not sure why the hash is different? We didn't do a hot fix...

**Comment by mikemhenry** [comment]
`RuntimeError: SHA256 mismatch: '51b57805dd26c0276dc48643b0beea4e2db2d7137e3b0f6931052c83d247b0c9' != 'f0de50d1641923ee25ad665c792993eaaa7faf7f844ac729e84fecf208ea504b'

`RuntimeError: SHA256 mismatch: '51b57805dd26c0276dc48643b0beea4e2db2d7137e3b0f6931052c83d247b0c9' != 'f0de50d1641923ee25ad665c792993eaaa7faf7f844ac729e84fecf208ea504b'`

Got the same mismatch so unlikely a network error, will need to compute it manually to fix this

**Comment by mikemhenry** [comment]
Still not sure why the sha256 hash changed. but did confirm locally that it needed to be changed:
`SHA256(/home/mmh/Downloads/perses-0.9.2.tar.gz)= 51b57805dd26c0276dc48643b0beea4e2db2d7137e3b0f6931052c83d247b0c9`

If this passes then we should be good to go!

**Comment by jaimergp** [comment]
> Still not sure why the sha256 hash changed

Github doesn't guarantee stable hashes in their tagged tarballs (e.g. finetuning the compression algorithm would change the hash). Only archived release artifacts are guaranteed to be immutable.

**Pull request merged**
